apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authenticationapi
    spec:
      containers:
      - name: mymicroservice
        image: [DOCKER ID]/authenticationapi:latest
        ports:
          - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: authenticationapi
---
#Change DOCKERID when deploying
apiVersion: v1
kind: Service
metadata:
  name: authenticationapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: authenticationapi